

spring:
  application:
    name: client-test2

#服务端口
server:
  port: 8091

# 注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7890/eureka/
  instance:
    prefer-ip-address: true
